### ISSUE TITLE
3.6節 関数オブジェクトについて

### ISSUE THREAD

**Issue by asei-proxima** [proxima-technology/casadi_mpc_nyuumon#2]
既に指摘されている箇所あるいは私の勘違いであればすみません。

私の手元にある第一刷の65ページにある下記のコード

```python
x = casadi.SX.sym("x", 4)
y = casadi.SX.sym("y", 1)
f = casadi.Function("f", [x, y], [2*x+y], ["x", "y"], ["2x"])
print(f)
```

ですが、最後の `f = ... ["2x"])` の `2x` の部分はなぜ `2x` になっていますか。文脈的には `2x+y` を計算しているので `"2x+y"` であるべきかと思いました。

**Comment by asei-proxima** [comment]
@th1991-01 Watchされていないようなのでメンションしておきます

**Comment by th1991-01** [comment]
@asei-proxima 
ご指摘ありがとうございます。

3章執筆担当の @da1996-04 に確認を取りますので、少々お待ちください。

**Comment by da1996-04** [comment]
@asei-proxima 
ご指摘ありがとうございます。
このコード例では出力に関する変数名を利用していないので、
基本的にはどのような文字列でも良いと考えてはいます。
ここでは64ページと同様に下記のように修正を行いました。

```python
x = casadi.SX.sym("x", 4)
y = casadi.SX.sym("y", 1)
f1 = 2*x + y
f = casadi.Function("f", [x, y], [f1], ["x", "y"], ["f1"])
print(f)
```

**Comment by da1996-04** [comment]
@asei-proxima 
ご指摘ありがとうございます。
このコード例では出力に関する変数名を利用していないので、
基本的にはどのような文字列でも良いと考えてはいます。
ここでは64ページと同様に下記のように修正を行いました。

```python
x = casadi.SX.sym("x", 4)
y = casadi.SX.sym("y", 1)
f1 = 2*x + y
f = casadi.Function("f", [x, y], [f1], ["x", "y"], ["f1"])
print(f)
```
