### ISSUE TITLE
5.1.2 倒立振子の運動方程式 の式 (5.2) について

### ISSUE THREAD

**Issue by asei-proxima** [proxima-technology/casadi_mpc_nyuumon#3]
既に指摘済みならすみません。

式 (5.2) の結論の式の $\dot{x}^2$ の係数が１になっていますが、 $M + m$ が正しそうです

**Comment by asei-proxima** [comment]
メンション @th1991-01 @da1996-04

**Comment by da1996-04** [comment]
@asei-proxima 
ご指摘頂きありがとうございます。

こちらについては仰る通りでございまして、第二版では修正をさせて頂いております。

ご指摘頂いた点も含めた初版時の誤りに関しては[こちら](https://github.com/proxima-technology/casadi_mpc_nyuumon/blob/master/%E6%AD%A3%E8%AA%A4%E8%A1%A8%E3%80%8EPython%E3%81%A8CasADi%E3%81%A7%E5%AD%A6%E3%81%B6%E3%83%A2%E3%83%87%E3%83%AB%E4%BA%88%E6%B8%AC%E5%88%B6%E5%BE%A1%E3%80%8F%EF%BC%88%E7%AC%AC1%E5%88%B7%E7%94%A8%EF%BC%89.pdf)の正誤表に記載しておりますので、
ご確認の程宜しくお願い致します。

**Comment by Seasawher** [comment]
正誤表あるんですね。確認します。

対応ありがとうございました
