### ISSUE TITLE
5.3.2 離散時間最適制御問題の有限次元パラメータ近似 について

### ISSUE THREAD

**Issue by asei-proxima** [proxima-technology/casadi_mpc_nyuumon#4]
@th1991-01 

p.90 の第二段落より

> 方針は区間 $[t_s, t_s + T]$ を均等に分割し，離散的な時間の量に関する記号の準備を行います.

日本語が変だと思います。（「方針は〜」から始まっているのに、「行います」で終わる。また、文の前半と後半で別の話をしていて、後半は方針とは関係がないように見える）

**Comment by th1991-01** [comment]
ご指摘ありがとうございます。
5章執筆担当の @da1996-04 に確認しますので、少々お待ちください。

**Comment by da1996-04** [comment]
@asei-proxima 
ご指摘頂きありがとうございます。

確かにここの文章は問題があるように思われます。

> 方針は区間 $[t_s, t_s + T]$ を均等に分割し，離散的な時間の量に関する記号の準備を行います.

とある文章を、

> まずは区間 $[t_s, t_s + T]$ を均等に分割し，各ステップにおける離散的な時間の量に関する記号の準備を行います.

のように変更させて頂きます。

こちらの文章の変更については、次回の修正にてご対応させていただきます。
