### ISSUE TITLE
5.3.4 最適化問題の時間離散化 について

### ISSUE THREAD

**Issue by asei-proxima** [proxima-technology/casadi_mpc_nyuumon#5]
@th1991-01 

これは指摘ではなく疑問ですが、共有するため issue として投稿します。

===

手元にある第２刷の92pで、 x_k と u_k について k の動く範囲が $0 \leq k \leq N$ になっているのですが、 $N$ とはなんですか？直前まで $k$ の上限は $K$ だったかと思います。

**Comment by asei-proxima** [comment]
2.2 節を参照してるので、2.2 節を見たところ、制御ホライズンの長さ $K$ よりも大きいかもしれない $N$ に対して、 $N$ ステップ目までの時間経過を考えたいということなのかと思いました。私としては解決しているので問題がなければクローズしてください。

（2.2 節では時間離散化の分割数と制御ホライズンの長さが一致しているので、 上記のように書いて問題がない）

**Comment by da1996-04** [comment]
@asei-proxima 
ご指摘ありがとうございます。

こちら $0 \leq k \leq N$ とあるのは、
$0 \leq k \leq K$ の誤りでした。

次回修正時にご対応させていただきます。
