### ISSUE TITLE
6.2 節 の `n_u` とはなにか

### ISSUE THREAD

**Issue by asei-proxima** [proxima-technology/casadi_mpc_nyuumon#9]
@th1991-01 

6.2.1 節の p.107 あたりに書かれているこの文章なのですが、

> ここで、制御軌道のパラメータ数は $n_{u} K$ であり, 有限次元です.

ここで言及されている $n_u$ とは何のことですか？

**Comment by th1991-01** [comment]
ご質問ありがとうございます。

制御入力 u の次元のことです。初出は１章8ページです。
> $u \in \mathbb{R}^{n_u}$を単に制御、あるいは制御変数または制御入力と呼びます。

その後、例えば以下のようなところで登場しています。
* 27ページ：決定変数の個数の個数は有限個（具体的には$n_x(K+1)+n_uK$個)
* 78ページ：`nu` は制御入力の次元

**Comment by asei-proxima** [comment]
ありがとうございます
